github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true

image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew assemble

jetbrains:
  intellij:
    prebuilds:
      version: stable
